server:
  port: 3333
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
spring:
  application:
    name: demo-clientsvc
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp